//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colectica.Curation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldDefinitions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldDefinitions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colectica.Curation.Web.Resources.FieldDefinitions", typeof(FieldDefinitions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AcceptedDate {
            get {
                return ResourceManager.GetString("AcceptedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any restrictions on access to or use of the collection such as privacy certification or distribution restrictions is indicated here..
        /// </summary>
        public static string AccessStatement {
            get {
                return ResourceManager.GetString("AccessStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity being analyzed in the study or in the variable.
        /// </summary>
        public static string AnalysisUnit {
            get {
                return ResourceManager.GetString("AnalysisUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ArchiveDate {
            get {
                return ResourceManager.GetString("ArchiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Principal Investigator or lead author and Name(s) of additional author(s).
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CatalogRecordCreator {
            get {
                return ResourceManager.GetString("CatalogRecordCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CertifiedDate {
            get {
                return ResourceManager.GetString("CertifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChecksumDate {
            get {
                return ResourceManager.GetString("ChecksumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChecksumMethod {
            get {
                return ResourceManager.GetString("ChecksumMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include a note about whether all or only some uploaded materials should be restricted. If some, indicate which files and the reason. E.g., “restrict access to “data.dta” because of geospatial information included or because of personally identified information (PII)..
        /// </summary>
        public static string ConfidentialityStatement {
            get {
                return ResourceManager.GetString("ConfidentialityStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contributor {
            get {
                return ResourceManager.GetString("Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original sources or documents from which data were obtained, e.g., Authors, U.S. Census (Dublin Core: Source).
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source contact information.
        /// </summary>
        public static string DataSourceInformation {
            get {
                return ResourceManager.GetString("DataSourceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of the data; kind of data documented in the logical product(s) of a study unit..
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign.
        /// </summary>
        public static string DepositAgreement {
            get {
                return ResourceManager.GetString("DepositAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief description or abstract of the study, project, published article, or data collection; Include a brief statement of the study hypotheses.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include a note about whether all or only some uploaded materials should be restricted due to a request for embargo, along with the month/year at which materials may be released..
        /// </summary>
        public static string EmbargoStatement {
            get {
                return ResourceManager.GetString("EmbargoStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExternalDatabase {
            get {
                return ResourceManager.GetString("ExternalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date(s) of data collection.
        /// </summary>
        public static string FieldDate {
            get {
                return ResourceManager.GetString("FieldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileTitle {
            get {
                return ResourceManager.GetString("FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormatID {
            get {
                return ResourceManager.GetString("FormatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormatName {
            get {
                return ResourceManager.GetString("FormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the funding agency and any additional information: date grant was received, grant number, etc..
        /// </summary>
        public static string FundingInformation {
            get {
                return ResourceManager.GetString("FundingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria for participant selection, or study sample construction, including eligibility, inclusion and exclusion criteria.
        /// </summary>
        public static string InclusionExclusionCriteria {
            get {
                return ResourceManager.GetString("InclusionExclusionCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe key details of the intervention and include all treatment groups. Include the number of intervention groups (enter 1 for single-arm study). Must be sufficiently detailed to distinguish between arms of a study and/or among similar interventions, and to describe any combinations of interventions; link to chart in cases where the intervention design is complicated..
        /// </summary>
        public static string Intervention {
            get {
                return ResourceManager.GetString("Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe how interventions were administered.
        /// </summary>
        public static string InterventionAdministration {
            get {
                return ResourceManager.GetString("InterventionAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsPublicAccess {
            get {
                return ResourceManager.GetString("IsPublicAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted due to confidential information.
        /// </summary>
        public static string IsRestrictedConfidential {
            get {
                return ResourceManager.GetString("IsRestrictedConfidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted due to embargo if materials should be embargoed for specified time period.
        /// </summary>
        public static string IsRestrictedEmbargo {
            get {
                return ResourceManager.GetString("IsRestrictedEmbargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted due to another reason.
        /// </summary>
        public static string IsRestrictedOther {
            get {
                return ResourceManager.GetString("IsRestrictedOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words or phrases that best describe the study, project, published article, or data collection. Keywords help users find studies in the database. Use controlled vocabulary terms where appropriate. Be as specific and precise as possible. Avoid acronyms and abbreviations..
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string KindOfData {
            get {
                return ResourceManager.GetString("KindOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LastUpdatedDate {
            get {
                return ResourceManager.GetString("LastUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location about which data were collected.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter more specific information such as country/countries. Only include information that may be made public in a catalog record; geospatial units at the level of small geographic areas such as villages may not be shared here..
        /// </summary>
        public static string LocationDetails {
            get {
                return ResourceManager.GetString("LocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe how data were collected.
        /// </summary>
        public static string ModeOfDataCollection {
            get {
                return ResourceManager.GetString("ModeOfDataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An organization-defined number for the item.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Institution with which the Author(s) is/are affiliated.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key measurement(s) or observation(s) used to measure the effect of experimental variables in a study, or for observational studies, measurement(s) or observation(s) that are a focus of the study (or the &quot;dependent variable&quot;); Include secondary and other measurements used to evaluate interventions, or, for observational studies, that are a focus of the study, excluding post-hoc measures..
        /// </summary>
        public static string OutcomeMeasures {
            get {
                return ResourceManager.GetString("OutcomeMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information for Author.
        /// </summary>
        public static string OwnerContact {
            get {
                return ResourceManager.GetString("OwnerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PersistentID {
            get {
                return ResourceManager.GetString("PersistentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PersistentLink {
            get {
                return ResourceManager.GetString("PersistentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PersistentLinkDate {
            get {
                return ResourceManager.GetString("PersistentLinkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PublicName {
            get {
                return ResourceManager.GetString("PublicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe how participants are allocated to intervention arms.
        /// </summary>
        public static string RandomizationProcedure {
            get {
                return ResourceManager.GetString("RandomizationProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data also deposited elsewhere (e.g., journal repository, institutional repository); Please provide a citation, DOI, or link.
        /// </summary>
        public static string RelatedDatabase {
            get {
                return ResourceManager.GetString("RelatedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of this study in a pre-analysis database (e.g., ClinicalTrials.gov, socialscienceregistry.org, http://egap.org/design-registration, etc.); Please provide a citation, DOI, or link.
        /// </summary>
        public static string RelatedProjects {
            get {
                return ResourceManager.GetString("RelatedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific publication using the data deposited here (journal articles, books, book chapters, government and agency reports, working papers, dissertations, conference papers, meeting presentations, unpublished manuscripts, magazine and newspaper articles, and audiovisual materials); Please provide a citation, DOI, or link.
        /// </summary>
        public static string RelatedPublications {
            get {
                return ResourceManager.GetString("RelatedPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RepresentationType {
            get {
                return ResourceManager.GetString("RepresentationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The overall strategy for addressing the research problem(s).
        /// </summary>
        public static string ResearchDesign {
            get {
                return ResourceManager.GetString("ResearchDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity that provided the information carried by the variable.
        /// </summary>
        public static string ResponseUnit {
            get {
                return ResourceManager.GetString("ResponseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReviewType {
            get {
                return ResourceManager.GetString("ReviewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of subjects in the study or number of observations (actual); Sample size; Number of cases in the final public dataset.
        /// </summary>
        public static string SampleSize {
            get {
                return ResourceManager.GetString("SampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SourceInformation {
            get {
                return ResourceManager.GetString("SourceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudyID {
            get {
                return ResourceManager.GetString("StudyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date(s) covered in the study, project, published article, or data collection.
        /// </summary>
        public static string StudyTimePeriod {
            get {
                return ResourceManager.GetString("StudyTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of this study, project, published article, or data collection.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of subjects in the study or number of observations (actual); Sample size; Number of cases in the final public dataset.
        /// </summary>
        public static string TotalObservations {
            get {
                return ResourceManager.GetString("TotalObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UniqueID {
            get {
                return ResourceManager.GetString("UniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who or what is being studied.
        /// </summary>
        public static string UnitOfObservation {
            get {
                return ResourceManager.GetString("UnitOfObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which units were randomized.
        /// </summary>
        public static string UnitOfRandomization {
            get {
                return ResourceManager.GetString("UnitOfRandomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UploadedDate {
            get {
                return ResourceManager.GetString("UploadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label each value for categorical variables.
        /// </summary>
        public static string VariableCategories {
            get {
                return ResourceManager.GetString("VariableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question wording or more information.
        /// </summary>
        public static string VariableDescription {
            get {
                return ResourceManager.GetString("VariableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VariableLastUpdated {
            get {
                return ResourceManager.GetString("VariableLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VariableVersion {
            get {
                return ResourceManager.GetString("VariableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VirusCheckDate {
            get {
                return ResourceManager.GetString("VirusCheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VirusCheckMethod {
            get {
                return ResourceManager.GetString("VirusCheckMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VirusCheckOutcome {
            get {
                return ResourceManager.GetString("VirusCheckOutcome", resourceCulture);
            }
        }
    }
}
