//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaleIsps.HandleService.YalePersistentLinkingService3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.ypls.dam.its.yale.edu/", ConfigurationName="YalePersistentLinkingService3.IPersistentLinking")]
    public interface IPersistentLinking {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchSemanticRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchSemanticResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        YaleIsps.HandleService.YalePersistentLinkingService3.resultMap createBatchSemantic(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string group, string user, string credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchSemanticRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchSemanticResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.resultMap> createBatchSemanticAsync(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string group, string user, string credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/modifyBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/modifyBatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        YaleIsps.HandleService.YalePersistentLinkingService3.resultMap modifyBatch(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string user, string credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/modifyBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/modifyBatchResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.resultMap> modifyBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string user, string credential);
        
        // CODEGEN: Parameter 'values' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/resolveBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/resolveBatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchResponse resolveBatch(YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/resolveBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/resolveBatchResponse")]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchResponse> resolveBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest request);
        
        // CODEGEN: Parameter 'values' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/deleteBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/deleteBatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchResponse deleteBatch(YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/deleteBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/deleteBatchResponse")]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchResponse> deleteBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest request);
        
        // CODEGEN: Parameter 'values' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
        YaleIsps.HandleService.YalePersistentLinkingService3.createBatchResponse createBatch(YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchRequest", ReplyAction="http://ws.ypls.dam.its.yale.edu/IPersistentLinking/createBatchResponse")]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.createBatchResponse> createBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ypls.dam.its.yale.edu/")]
    public partial class handleMap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private handleMapEntry[] mapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public handleMapEntry[] map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("map");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.ypls.dam.its.yale.edu/")]
    public partial class handleMapEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ypls.dam.its.yale.edu/")]
    public partial class resultMap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultMapEntry[] failMapField;
        
        private resultMapEntry1[] successMapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public resultMapEntry[] failMap {
            get {
                return this.failMapField;
            }
            set {
                this.failMapField = value;
                this.RaisePropertyChanged("failMap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public resultMapEntry1[] successMap {
            get {
                return this.successMapField;
            }
            set {
                this.successMapField = value;
                this.RaisePropertyChanged("successMap");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.ypls.dam.its.yale.edu/")]
    public partial class resultMapEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.ypls.dam.its.yale.edu/")]
    public partial class resultMapEntry1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resolveBatch", WrapperNamespace="http://ws.ypls.dam.its.yale.edu/", IsWrapped=true)]
    public partial class resolveBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] values;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string credential;
        
        public resolveBatchRequest() {
        }
        
        public resolveBatchRequest(string[] values, string user, string credential) {
            this.values = values;
            this.user = user;
            this.credential = credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resolveBatchResponse", WrapperNamespace="http://ws.ypls.dam.its.yale.edu/", IsWrapped=true)]
    public partial class resolveBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap results;
        
        public resolveBatchResponse() {
        }
        
        public resolveBatchResponse(YaleIsps.HandleService.YalePersistentLinkingService3.resultMap results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteBatch", WrapperNamespace="http://ws.ypls.dam.its.yale.edu/", IsWrapped=true)]
    public partial class deleteBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] values;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string credential;
        
        public deleteBatchRequest() {
        }
        
        public deleteBatchRequest(string[] values, string user, string credential) {
            this.values = values;
            this.user = user;
            this.credential = credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteBatchResponse", WrapperNamespace="http://ws.ypls.dam.its.yale.edu/", IsWrapped=true)]
    public partial class deleteBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap results;
        
        public deleteBatchResponse() {
        }
        
        public deleteBatchResponse(YaleIsps.HandleService.YalePersistentLinkingService3.resultMap results) {
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createBatch", WrapperNamespace="http://ws.ypls.dam.its.yale.edu/", IsWrapped=true)]
    public partial class createBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] values;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string credential;
        
        public createBatchRequest() {
        }
        
        public createBatchRequest(string[] values, string group, string user, string credential) {
            this.values = values;
            this.group = group;
            this.user = user;
            this.credential = credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createBatchResponse", WrapperNamespace="http://ws.ypls.dam.its.yale.edu/", IsWrapped=true)]
    public partial class createBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap results;
        
        public createBatchResponse() {
        }
        
        public createBatchResponse(YaleIsps.HandleService.YalePersistentLinkingService3.resultMap results) {
            this.results = results;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersistentLinkingChannel : YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersistentLinkingClient : System.ServiceModel.ClientBase<YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking>, YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking {
        
        public PersistentLinkingClient() {
        }
        
        public PersistentLinkingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersistentLinkingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistentLinkingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersistentLinkingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap createBatchSemantic(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string group, string user, string credential) {
            return base.Channel.createBatchSemantic(handlesToValues, group, user, credential);
        }
        
        public System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.resultMap> createBatchSemanticAsync(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string group, string user, string credential) {
            return base.Channel.createBatchSemanticAsync(handlesToValues, group, user, credential);
        }
        
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap modifyBatch(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string user, string credential) {
            return base.Channel.modifyBatch(handlesToValues, user, credential);
        }
        
        public System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.resultMap> modifyBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.handleMap handlesToValues, string user, string credential) {
            return base.Channel.modifyBatchAsync(handlesToValues, user, credential);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchResponse YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking.resolveBatch(YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest request) {
            return base.Channel.resolveBatch(request);
        }
        
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap resolveBatch(string[] values, string user, string credential) {
            YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest inValue = new YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest();
            inValue.values = values;
            inValue.user = user;
            inValue.credential = credential;
            YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchResponse retVal = ((YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking)(this)).resolveBatch(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchResponse> YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking.resolveBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest request) {
            return base.Channel.resolveBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchResponse> resolveBatchAsync(string[] values, string user, string credential) {
            YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest inValue = new YaleIsps.HandleService.YalePersistentLinkingService3.resolveBatchRequest();
            inValue.values = values;
            inValue.user = user;
            inValue.credential = credential;
            return ((YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking)(this)).resolveBatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchResponse YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking.deleteBatch(YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest request) {
            return base.Channel.deleteBatch(request);
        }
        
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap deleteBatch(string[] values, string user, string credential) {
            YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest inValue = new YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest();
            inValue.values = values;
            inValue.user = user;
            inValue.credential = credential;
            YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchResponse retVal = ((YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking)(this)).deleteBatch(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchResponse> YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking.deleteBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest request) {
            return base.Channel.deleteBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchResponse> deleteBatchAsync(string[] values, string user, string credential) {
            YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest inValue = new YaleIsps.HandleService.YalePersistentLinkingService3.deleteBatchRequest();
            inValue.values = values;
            inValue.user = user;
            inValue.credential = credential;
            return ((YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking)(this)).deleteBatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YaleIsps.HandleService.YalePersistentLinkingService3.createBatchResponse YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking.createBatch(YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest request) {
            return base.Channel.createBatch(request);
        }
        
        public YaleIsps.HandleService.YalePersistentLinkingService3.resultMap createBatch(string[] values, string group, string user, string credential) {
            YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest inValue = new YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest();
            inValue.values = values;
            inValue.group = group;
            inValue.user = user;
            inValue.credential = credential;
            YaleIsps.HandleService.YalePersistentLinkingService3.createBatchResponse retVal = ((YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking)(this)).createBatch(inValue);
            return retVal.results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.createBatchResponse> YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking.createBatchAsync(YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest request) {
            return base.Channel.createBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<YaleIsps.HandleService.YalePersistentLinkingService3.createBatchResponse> createBatchAsync(string[] values, string group, string user, string credential) {
            YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest inValue = new YaleIsps.HandleService.YalePersistentLinkingService3.createBatchRequest();
            inValue.values = values;
            inValue.group = group;
            inValue.user = user;
            inValue.credential = credential;
            return ((YaleIsps.HandleService.YalePersistentLinkingService3.IPersistentLinking)(this)).createBatchAsync(inValue);
        }
    }
}
